# Generated by Django 3.1.7 on 2021-10-02 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deletion Date')),
                ('module_type', models.PositiveSmallIntegerField(choices=[(1, 'Personal Growth'), (2, 'Chat Bot'), (3, 'Simpl Deconstructor'), (4, 'Date Simulation'), (5, 'Sex Secrets'), (6, 'Environment Dominance')], default=1, verbose_name='Module Type')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='HistoricalModule',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Creation Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Update Date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deletion Date')),
                ('module_type', models.PositiveSmallIntegerField(choices=[(1, 'Personal Growth'), (2, 'Chat Bot'), (3, 'Simpl Deconstructor'), (4, 'Date Simulation'), (5, 'Sex Secrets'), (6, 'Environment Dominance')], default=1, verbose_name='Module Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Module',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCard',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Creation Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Update Date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deletion Date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('completed', models.BooleanField(default=False)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'WHITE'), (2, 'GREEN'), (3, 'BLUE'), (4, 'PURPLE'), (5, 'ORANGE'), (6, 'RED')], default=1, verbose_name='Rarity')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card_module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cards.module', verbose_name='Card Module')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Card',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deletion Date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('completed', models.BooleanField(default=False)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'WHITE'), (2, 'GREEN'), (3, 'BLUE'), (4, 'PURPLE'), (5, 'ORANGE'), (6, 'RED')], default=1, verbose_name='Rarity')),
                ('card_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.module', verbose_name='Card Module')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
